pipeline {

    agent {
        label 'docker-worker'
    }

    environment {
        IMAGE_NAME = "easymovies"
        COMPOSE_PROJECT_NAME = "easymovies"
    }

    options {
        timestamps()
    }

    stages {

        stage('Checkout Source') {
            steps {
                checkout scm
            }
        }

        stage('Environment Information') {
            steps {
                sh '''
                    echo "===== Build Environment ====="
                    hostname
                    whoami
                    pwd
                    git --version
                    docker --version
                    docker compose version
                '''
            }
        }
        stage('Debug Workspace') {
            steps {
                sh '''
                    echo "Current directory:"
                    pwd

                    echo "Workspace contents:"
                    ls -la

                    echo "Find Dockerfile:"
                    find . -name Dockerfile

                    echo "Find Jenkinsfile:"
                    find . -name Jenkinsfile
                '''
            }
        }
        stage('Build Docker Image') {
            steps {
                sh '''
                   cd easymovies
                   docker build -t easymovies:${BUILD_NUMBER} -t easymovies:latest .
                '''
            }
        }

        stage('Run Unit Tests') {
            steps {
                sh '''
                    docker run --rm -w /app -e PYTHONPATH=/app easymovies:${BUILD_NUMBER} pytest -v
                '''
            }
        }

        stage('Deploy Application') {
            steps {
                sh '''
                    cd easymovies
                    export IMAGE_TAG=${BUILD_NUMBER}
                    export GIT_COMMIT=$(git rev-parse --short HEAD)
                    export BUILD_URL=${BUILD_URL}
                    export BUILD_NUMBER=${BUILD_NUMBER}
                    export GIT_COMMIT=$(git rev-parse --short HEAD)
                    export BUILD_USER=${BUILD_USER_ID:-jenkins}
                    export BUILD_TIME="$(date)"
                    docker compose up -d
                '''
            }
        }

        stage('Smoke Test') {
            steps {
                sh '''
                    echo "Waiting for application..."
                    sleep 10

                    curl --fail http://localhost:8081

                    echo "Smoke test passed."
                '''
            }
        }

        stage('Push Image to DockerHub.Update your repo name instead of easymovies in your Dockerhub Account') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'DOCKER_PASS',    //Update with credentials ID
                    usernameVariable: 'DOCKER_USER',  
                    passwordVariable: 'DOCKER_PASS'  
                )]) {
        
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker tag easymovies:${BUILD_NUMBER} $DOCKER_USER/easymovies:${BUILD_NUMBER}   
                        docker push $DOCKER_USER/easymovies:${BUILD_NUMBER}
                        docker logout
                        echo "Image Uplaoded successfully to $DOCKER_USER/easymovies:${BUILD_NUMBER}"
                    '''
                }
            }
        }        
        
// withCredentials([[
//     $class: 'AmazonWebServicesCredentialsBinding',
//     credentialsId: 'aws-creds'
// ]]) {

//     sh '''
//         aws sts get-caller-identity
//         aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 123456789012.dkr.ecr.us-east-1.amazonaws.com
//         docker tag easymovies:${BUILD_NUMBER}   123456789012.dkr.ecr.us-east-1.amazonaws.com/easymovies:${BUILD_NUMBER}
//         docker push  123456789012.dkr.ecr.us-east-1.amazonaws.com/easymovies:${BUILD_NUMBER}
//     '''
// }
        stage('Show Running Containers') {
            steps {
                sh '''
                    docker ps
                '''
            }
        }
    }

    post {
        always {
            echo "Finishing the pipeline execution. "
        }
        success {
            echo "SUCCESS: EasyMovies deployed successfully."
        }
        failure {
            echo "FAILED: Pipeline execution failed."
        }
    }
}
